apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: snutt-dev
  namespace: argocd
spec:
  description: snutt-dev
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
    - group: ''
      kind: Service
  orphanedResources:
    warn: false
  roles:
    - name: snutt-server
      description: snutt-server
      policies:
        - p, proj:snutt-dev:snutt-server, applications, *, snutt-dev/*, allow
      groups:
        - wafflestudio/snutt-server
    - name: snutt-frontend
      description: snutt-frontend
      policies:
        - p, proj:snutt-dev:snutt-frontend, applications, *, snutt-dev/*, allow
      groups:
        - wafflestudio/snutt-frontend
