apiVersion: apps/v1
kind: Deployment
metadata:
  name: snutt-core
  labels:
    app: snutt-core
  namespace: snutt-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snutt-core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: snutt-core
    spec:
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt/snutt-server:latest-dev
        imagePullPolicy: Always
        name: snutt-ev
        ports:
        - containerPort: 3000
