apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: snutt-ev-web-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wafflestudio/waffle-world.git
    targetRevision: HEAD
    path: apps/snutt-dev/snutt-ev-web
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
