apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: snutt-ev-web
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wafflestudio/waffle-world.git
    targetRevision: HEAD
    path: apps/snutt-dev/snutt-ev-web
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snutt-ev-web
  labels:
    app: snutt-ev-web
  namespace: snutt-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snutt-ev-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: snutt-ev-web
    spec:
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt/snutt-ev-web:latest-dev
        imagePullPolicy: Always
        name: snutt-ev-web
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: snutt-dev
  name: snutt-ev-web
spec:
  type: NodePort
  selector:
    app: snutt-ev-web
  ports:
  - port: 80
    targetPort: 3000
